version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/backend/HealthLens.Api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/backend/HealthLens.Tests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
