// Side-effect imports that register the official @material/web custom elements used in this app.
// Import this once (from main.tsx) rather than scattering imports across every component.
import '@material/web/button/filled-button.js'
import '@material/web/button/outlined-button.js'
import '@material/web/button/text-button.js'
import '@material/web/button/filled-tonal-button.js'
import '@material/web/textfield/outlined-text-field.js'
import '@material/web/iconbutton/icon-button.js'
import '@material/web/icon/icon.js'
import '@material/web/progress/linear-progress.js'
import '@material/web/progress/circular-progress.js'
import '@material/web/radio/radio.js'
import '@material/web/switch/switch.js'
import '@material/web/checkbox/checkbox.js'
import '@material/web/divider/divider.js'
